[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "link-args=-pthread", # was -sUSE_PTHREADS=1 in earlier emscripten versions
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-Zlink-native-libraries=no",
    "-Clink-arg=-fwasm-exceptions",
    "-Clink-args=-sDISABLE_EXCEPTION_CATCHING=1",
    "-Clink-args=-sEXPORT_ALL=1",
    "-Clink-args=-sSUPPORT_LONGJMP=wasm",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
    "-Cllvm-args=-wasm-enable-sjlj",
]

